Simplify initialize-image-patch validation

diff --git a/emulator/bin/initialize-image-patch b/emulator/bin/initialize-image-patch
--- a/emulator/bin/initialize-image-patch
+++ b/emulator/bin/initialize-image-patch
@@ -42,7 +42,7 @@ rm-busybox-upload "${ROOTDIR}/artifact/rm2fb.tar.gz" /tmp
 rm-busybox-upload "${ROOTDIR}/artifact/rm-qemu-emergency.service" /tmp
 for dev in A B; do
   echo "Setting up root$dev partition..."
-  rm-busybox-exec <<'EOF'
+  rm-busybox-exec <<EOF
     set -e
     cd /mnt/root${dev}
     tar xzhf /tmp/rm2fb.tar.gz -C .
@@ -53,7 +53,6 @@ for dev in A B; do
     mkdir -p etc/systemd/system/xochitl.service.d
 
     cp -f /tmp/id_rsa.pub etc/dropbear/authorized_keys
-    printf 'DROPBEAR_EXTRA_ARGS=" -B"\n' > etc/default/dropbear
     mkdir -p etc/skel/.ssh/
     chmod 0700 etc/skel/.ssh/
     cp -f /tmp/id_rsa.pub etc/skel/.ssh/authorized_keys
@@ -97,27 +96,20 @@ EOF
     rm-busybox-exec sed -i 's/wlan/eth/' /mnt/root${dev}/lib/systemd/system/dhcpcd.service
   fi
 done
-password=$(rm-askpass)
 rm-busybox-exec <<EOF
   set -e
   cd /mnt
   mkdir -p home/root/.config/remarkable/
   cp -a rootA/etc/skel/. home/root
   echo "[General]" > home/root/.config/remarkable/xochitl.conf
-  echo "DeveloperPassword=${password}" >> home/root/.config/remarkable/xochitl.conf
+  echo "DeveloperPassword=$(rm-askpass)" >> home/root/.config/remarkable/xochitl.conf
   echo "/dev/mmcblk1  /var/log  ext4  defaults,x-systemd.before=systemd-journald.service 0 0" >> rootA/etc/fstab
   echo "/dev/mmcblk1  /var/log  ext4  defaults,x-systemd.before=systemd-journald.service 0 0" >> rootB/etc/fstab
   for d in A B; do
-    if [ "$(cat root${d}/etc/default/dropbear)" != 'DROPBEAR_EXTRA_ARGS=" -B"' ]; then
-      echo "ERROR: root${d}/etc/default/dropbear corruption detected" >&2
-      exit 1
-    fi
-    if ! cmp -s /tmp/id_rsa.pub root${d}/etc/skel/.ssh/authorized_keys; then
-      echo "ERROR: root${d}/etc/skel/.ssh/authorized_keys mismatch vs source" >&2
-      exit 1
-    fi
-    if ! cmp -s /tmp/id_rsa.pub root${d}/etc/dropbear/authorized_keys; then
-      echo "ERROR: root${d}/etc/dropbear/authorized_keys mismatch vs source" >&2
+    if [ "$(cat root${d}/etc/default/dropbear)" != 'DROPBEAR_EXTRA_ARGS=" -B"']
+        || ! cmp -s /tmp/id_rsa.pub root${d}/etc/skel/.ssh/authorized_keys
+        || ! cmp -s /tmp/id_rsa.pub root${d}/etc/dropbear/authorized_keys; then
+      echo "ERROR: root${d} ssh files are corrupted" >&2
       exit 1
     fi
   done
