Fix validation: escape variables, remove dropbear check

diff --git a/emulator/bin/initialize-image-patch b/emulator/bin/initialize-image-patch
--- a/emulator/bin/initialize-image-patch
+++ b/emulator/bin/initialize-image-patch
@@ -106,10 +106,9 @@ rm-busybox-exec <<EOF
   echo "/dev/mmcblk1  /var/log  ext4  defaults,x-systemd.before=systemd-journald.service 0 0" >> rootA/etc/fstab
   echo "/dev/mmcblk1  /var/log  ext4  defaults,x-systemd.before=systemd-journald.service 0 0" >> rootB/etc/fstab
   for d in A B; do
-    if [ "$(cat root${d}/etc/default/dropbear)" != 'DROPBEAR_EXTRA_ARGS=" -B"']
-        || ! cmp -s /tmp/id_rsa.pub root${d}/etc/skel/.ssh/authorized_keys
-        || ! cmp -s /tmp/id_rsa.pub root${d}/etc/dropbear/authorized_keys; then
-      echo "ERROR: root${d} ssh files are corrupted" >&2
+    if ! cmp -s /tmp/id_rsa.pub root\${d}/etc/skel/.ssh/authorized_keys
+        || ! cmp -s /tmp/id_rsa.pub root\${d}/etc/dropbear/authorized_keys; then
+      echo "ERROR: root\${d} ssh files are corrupted" >&2
       exit 1
     fi
   done
